#!/bin/bash
ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_full -font "Monoisome 16" -m 0 -fullscreen)


select=$(echo "MOUNT
UNMOUNT" | awk '{print $(NF-1)}' | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "Choose to: ")

if [ "$select" == "MOUNT" ] ; then
	#mountable=$(lsblk -lp | grep part | grep -v "t /" | awk '{print $1, "(" $4 ")"}')
	mountable=$(lsblk -rpo "name,type,size,mountpoint" | awk '$2=="part"&&$4==""{printf "%s (%s)\n",$1,$3}')
	mountdrive=$(echo "$mountable" | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "Choose drive to mount: " | awk '{print $1}');
	[[ -z $mountdrive ]] && echo "exiting 1" && exit
	directory=$(find /media /home -type d -maxdepth 3 2>/dev/null)
	mountpoint=$(echo "$directory" | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "Choose mounting directory: ");
	[[ -z $mountpoint ]] && echo "exiting 2" && exit
	[[ ! -d "$mountpoint" ]] &&	prompt=$(echo -e "No\nYes" | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p  "Create $mountpoint?");
	[[ "$prompt" = No ]] && echo "exiting 3" && notify-send "Mounted" "$mountdrive was mounted on $mountpoint" && exit
	SUDO_ASKPASS=~/.scripts/tools/askpass sudo -A mkdir -p $mountpoint && sudo mount $mountdrive $mountpoint
	notify-send "Mounted" "$mountdrive was mounted on $mountpoint"
fi

if [ "$select" == "UNMOUNT" ] ; then
	#mounted=$(lsblk -lp | grep "t /" | grep -v "\(/boot\|/home\|/\)$" | awk '{print $1, "(" $4 ")", "on", $7}')
	mounted=$(lsblk -nrpo "name,type,size,mountpoint" | awk '$2=="part"&&$4!~/\/boot|\/home$|SWAP/&&length($4)>1{printf "%s (%s)\n",$4,$3}')
	unmountdrive=$(echo "$mounted" | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "Choose drive to unmount: ");
	[[ -z $unmountdrive ]] && echo "exiting 4" && notify-send "Unmounted" "$unmountdrive was unmounted" && exit
	drive=$(echo $unmountdrive | awk '{print $1}')
	folder=$(echo $unmountdrive | awk '{print $4}')
	SUDO_ASKPASS=~/.scripts/tools/askpass sudo -A umount $drive && sudo -A rm -r $folder
	notify-send "Unmounted" "$unmountdrive was unmounted"
fi
