#!/bin/sh
#              _            _             _   
#   __ _ _   _| |_ ___  ___| |_ __ _ _ __| |_ 
#  / _` | | | | __/ _ \/ __| __/ _` | '__| __|
# | (_| | |_| | || (_) \__ \ || (_| | |  | |_ 
#  \__,_|\__,_|\__\___/|___/\__\__,_|_|   \__|
# --------------------------------------------

# start sxhkd
sxhkd &

# Load xresources
xrdb merge .Xresources &

# audio
start-pulseaudio-x11 &

# run dunst to show notifications
dunst &

# background
sh ~/.fehbg &

# compositing (shadows, transparency, reduced flickering)
picom -b &

# enable local fonts in .fonts directory
xset +fp /usr/share/fonts/local &
xset +fp /usr/share/fonts/misc &
xset +fp ~/.fonts &
xset fp rehash &
fc-cache -fv &

# powersaving options
xset s off &
xset s noblank &
xset s noexpose &
xset c on &
xset -dpms &

# remove x cursor symbol on background hover
xsetroot -cursor_name left_ptr &

# blue light remover
redshift &

# use arandr monitor settings
$HOME/.config/arandr.sh &

# launch polybar
$HOME/.config/polybar/launch.sh &
