#!/bin/sh

#  _                                 
# | |__  ___ _ ____      ___ __ ___  
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \ 
# | |_) \__ \ |_) \ V  V /| | | | | |
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#           |_|                      
# -----------------------------------

# Gaps
# -----------------------------------
gap=15
PANEL_HEIGHT=35
export gap
#This creates negative padding equal to window gap so that gaps are shown only between windows and not on desktop edges.
bspc config window_gap $gap;
bspc config top_padding $gap
bspc config left_padding -$gap
bspc config right_padding -$gap
bspc config bottom_padding $(($PANEL_HEIGHT+$gap))

# Color settings
# -----------------------------------
bspc config focused_border_color "#1ABB9B"
bspc config normal_border_color "#222D32"
bspc config presel_feedback_color "#1ABB9B"
bspc config border_width 3

# Specific Application Settings
# -----------------------------------
bspc rule -a $PLAYER state=pseudo_tiled
bspc rule -a $BROWSER private=on

# Misc Settings
# -----------------------------------
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
# move mouse with selecting windows
bspc config focus_follows_pointer true
# Honor size hints: do not make windows smaller than they wish to be
#bspc config honor_size_hints true 

# run autoload
$HOME/.config/bspwm/autostart &










# todo: below
###This creates and names desktops for multiple monitors.
workspaces_multimonitor &

##  Autogap adjusts windowgap automatically according to the number of
##  windows on the desktop. Using it disables negative window gap.
#autogap &

##  This script balances all windows when new one is spawned 
#euclid_balancer &

##Edge-switcher switches to next workspace when moves moves to the 
##edge of the monitor (behavior similar to enlightenment)
#edge-switcher &

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
bspc config external_rules_command /usr/bin/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command /usr/bin/adjust-new-window
